### ISSUE TITLE
link in readme is invalid 

### ISSUE THREAD

**Issue by sachincool** [thakursaurabh1998/cpp#1]
link in readme is invalid 

> * In the Older > Constructor example in readme

`https://github.com/thakursaurabh1998/cpp/blob/master/constructor.cpp` 
shouldbe 
`https://github.com/thakursaurabh1998/cpp/blob/master/contructors.cpp`

**Comment by thakursaurabh1998** [comment]
Will be corrected in the next push.
Thankyou.
